version: '3.4'
services:

  backend-test:
    image: misieq/weii_ai_aplikacja_testujaca_backend
    container_name: backend-testapp
    restart: unless-stopped
    volumes:
      - ./backend/src/:/app/
    environment:
      - DJANGO_SUPERUSER_PASSWORD=admin 
      - LC_TIME="pl_PL"
    command: python3 ./manage.py runserver 0.0.0.0:8002
    ports: 
      - 8002:8002

  frontend-test:
    image: misieq/weii_ai_aplikacja_testujaca_frontend
    container_name: frontend-testapp
    restart: unless-stopped
    environment:
      - LC_TIME="pl_PL"
    ports:
      - 8082:8080
    depends_on:
      - backend-test
