version: '3.5'
services:

  backend-test:
    build:
      context: ./backend/	
      network: host
    restart: unless-stopped
    volumes:
      - ./backend/src/:/app/
    environment:
      - DJANGO_SUPERUSER_PASSWORD=admin
      - BACKEND_URL="http://127.0.0.1:8002"
      - BACKEND_USER="admin"
      - BACKEND_PASSWORD="admin" 
      - LC_TIME="pl_PL"
    command: sh -c 'python3 ./manage.py seed_test &&  python3 ./manage.py runserver 0.0.0.0:8002'
    ports: 
      - 8002:8002
    depends_on:
      - rabbitmq
    networks:	
      - test_over
      
  frontend-test:
    build:
      context: ./frontend/	
      network: host
    restart: unless-stopped
    environment:
      - LC_TIME="pl_PL"
    ports:
      - 8082:8080
    depends_on:
      - backend-test
    networks:	
      - test_over
      
      
  celery:
    build:
      context: ./backend/	
      network: host
    command: celery -A api_client  worker -l info
    environment:
      - CELERY_BROKER_URL=amqp://bitnami:bitnami@rabbitmq:5673
      - BACKEND_URL="http://127.0.0.1:8002"
      - BACKEND_USER="admin"
      - BACKEND_PASSWORD="admin"
      - LC_TIME="pl_PL"
    volumes:
      - ./backend/src/:/app/
    depends_on:
      - frontend-test
    networks:	
      - test_over
      
      
  rabbitmq:
    hostname: rabbit
    image: bitnami/rabbitmq
    environment:
        - RABBITMQ_MANAGER_PORT_NUMBER=15673
        - RABBITMQ_NODE_PORT_NUMBER=5673
        - RABBITMQ_USERNAME=bitnami
        - RABBITMQ_PASSWORD=bitnami
        - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5673
        - LC_TIME="pl_PL"
    ports:
        - "15673:15673"  
        - "5673:5673"
    networks:	
      - test_over
      
networks:	
  test_over:
    external:
      name: over
